companies:
  - name: American Express
    platform: eightfold
    api_url: "https://aexp.eightfold.ai/api/apply/v2/jobs/40416958/jobs?domain=aexp.com"
    keywords:
      - Security
      - SOC
      - Cyber
      - Analyst
      - Technology Operations Engineering